version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: ems_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: ems_database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ems_backend
    restart: always
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - DATABASE_URL=postgresql://postgres:admin1234@postgres_db:5432/ems_database?schema=public
      - JWT_SECRET=supersecretjwtkey1234!
      - NODE_ENV=production
    depends_on:
      - postgres_db

volumes:
  pgdata:
